### ISSUE TITLE
Strike price with decimal places

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#1]
The frontend app is failing to display/query prices for options whose strike price contains decimal places.

Here is one example:
![image](https://user-images.githubusercontent.com/2445889/116837340-6dc9f080-aba0-11eb-9936-b54dd3235dc5.png)

The image shows the expected result for querying the buy price of an EUR/USD put option with strike price US$ 1.15

As it appears, the frontend app is not currently able to handle this option symbol.

**Comment by remote-gildor** [comment]
Noted, I'll check it out 👍

**Comment by remote-gildor** [comment]
Fixed in this commit: https://github.com/DeFiOptions/DeFiOptions-frontend/commit/d2ff9c2c1d7f96028a25f02e9ea671137c3fedfd
