### ISSUE TITLE
Sell option modal out of sync

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#10]
After selling the option successfully, the window to sell does not go away and as a end user I may click again on sell. It throws exception as shown in screenshot

![image](https://user-images.githubusercontent.com/2445889/125085711-43654980-e0a1-11eb-9589-484bd7925608.png)

Reported by: Vishal_Mehta#5736

**Comment by remote-gildor** [comment]
done 👍
