### ISSUE TITLE
Reset Yield for soft launch

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#26]
We need to reset the pool yield back to "0%" for the soft launch.

For that, simply divide the yield readings by the pre-launch yield, currently at `1262535945`:

<img width="200" src="https://user-images.githubusercontent.com/2445889/142291975-a8a4c239-f814-4ec8-ab7b-185f2a1c343e.png"/>

The code lines that need change are located here: https://github.com/DeFiOptions/DeFiOptions-frontend/blob/4c4256ec7a0ff15cd1216dbd467f0ba282a91c21/src/store/modules/liquidityPool.js#L76-L77

Proposed change:

```
    let base = 1262535945;
    let apy = await state.contract.methods.yield(365 * 24 * 60 * 60).call();
    let apyBig = (apy / base  - 1) * 100;
```

**Comment by remote-gildor** [comment]
Implemented in this commit: https://github.com/DeFiOptions/DeFiOptions-frontend/commit/1d70899bdede30d765c92e2a07dd6cb60c467f02 

Although the question about the constant vs. variable base value remains, as we've discussed on Discord... So I'll keep this issue open for a while.
