### ISSUE TITLE
MetaMask wallet stuck on mobile

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#28]
From my metamask mobile I get stuck with this screen when pressing ”connect wallet:

<img width="240" src="https://user-images.githubusercontent.com/2445889/142521218-62527c7c-2361-420f-82b0-8fec2c2de23e.png"/>

Reported by: `badgerton#1410`
Reproduced by: `Mr. Rock#5540`

**Comment by remote-gildor** [comment]
fixed
