### ISSUE TITLE
Refresh outdated option price before buying / selling

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#30]
In polygon a new block is mined every two seconds. Options prices can change more than the hardcoded 1% slippage in between a few blocks and when that happens the buy/sell operation will show an error in MetaMask:

To improve the UX we should re-check the option price right before executing the operation in MetaMask in case it's outdated, i.e. older than a predetermined period of time (for instance, 10 seconds). In case the new price invalidates the operation, the user should be notified about the updated price, and decide whether he/she wishes to continue or not.

Code reference for updating the price:
- https://github.com/DeFiOptions/DeFiOptions-frontend/blob/f60db25947b8946e58b9dc1813888eae9173e4ea/src/components/trade/Option.vue#L117

Reported by: Whipper#1745

**Comment by remote-gildor** [comment]
Done, and I also increased slippage to 2%: https://github.com/DeFiOptions/DeFiOptions-frontend/commit/1e89e93b3538a4a73267aea61211261e95baeaf9
