### ISSUE TITLE
Allow infinite approval

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#31]
We received user feedback requesting the infinite approval feature in the UI, so that they won't need to individually approve limited amounts for every operation in DeFi Options:

![image](https://user-images.githubusercontent.com/2445889/142951123-c6cf92fe-641e-45a2-a8f1-74021ae297fb.png)

**Comment by remote-gildor** [comment]
How do we place this in the UI?

**Comment by TCGV** [comment]
Here's a proposal:

![image](https://user-images.githubusercontent.com/2445889/143681985-d9b61f13-47d7-4074-a2d7-95cc554dc83c.png)

If the user clicks the Link below the button will switch to **APPROVE USDC** and the bottom text would change to:

- "click here to use limited approval"

This way the user can switch back and forth between infinite and limited approval when trading options.

**Comment by remote-gildor** [comment]
Option to select unlimited allowance added, but through a modal.
