### ISSUE TITLE
Underlying price doesn't update

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#33]
Switching from btc/usd to eth/usd when there are no puts available for eth/usd, the current price doesn't update

https://www.loom.com/share/833df9de7ab54114816a1c6817d25110

Reported by: obasilakis#6197

**Comment by remote-gildor** [comment]
@TCGV The problem is that `symbol` is needed as a parameter when calling the `getUnderlyingPrice()` function in Options Exchange.

In the video, there were no ETH PUT options, so there was no `symbol` that could be sent as param to `getUnderlyingPrice()`.

**Comment by TCGV** [comment]
> @TCGV The problem is that `symbol` is needed as a parameter when calling the `getUnderlyingPrice()` function in Options Exchange.
> 
> In the video, there were no ETH PUT options, so there was no `symbol` that could be sent as param to `getUnderlyingPrice()`.

I see. In that case no underlying price should be displayed.

Actually, whenever the selected underlying market is changed, the corresponding underlying price should be cleared immediately to avoid confusion, because sometimes there's a delay in the UI for fetching the current underlying price, and it could even fail (network error) and we don't want incorrect prices showing.
