### ISSUE TITLE
Infinite Approval verification issue

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#34]
I believe there's a minor bug in the implementation:

1) Approve infinite USDC allowance
2) Wait for Tx confirmation
3) Buy option using USDC 
4) Wait for Tx confirmation
5) The UI defaults back to the "approve USDC" button

![image](https://user-images.githubusercontent.com/2445889/143791892-8333abf8-a58b-4e06-a338-b2049835dd88.png)

Only after refreshing the page (hitting F5) that the frontend app detects that there's no need for another approval for buying options with USDC:

![image](https://user-images.githubusercontent.com/2445889/143791920-fde63220-5afe-478c-8e2b-8b66e0b01fb2.png)

**Comment by remote-gildor** [comment]
Weird, I haven't experienced this issue. Did it happen on Kovan or on Polygon?
