### ISSUE TITLE
Incorrect maturity timezone

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#35]
The option maturity date is being automatically converted to my timezone by Chrome, which in my case isn't UTC:

![image](https://user-images.githubusercontent.com/2445889/143937806-e420d680-8375-4977-8ad2-24040907b889.png)

Here's the paresed timestamp, both in UTC and in my current timezone:

![image](https://user-images.githubusercontent.com/2445889/143938406-17594ce7-0c89-4538-9d0a-501b904388e5.png)

So we need to check the parsed timestamp timezone before appending the `'(UTC)'` suffix, which in my case isn't necessary:

- https://github.com/DeFiOptions/DeFiOptions-frontend/blob/78597709778d01fa4809a24d168c2481ebcc5eb2/src/store/modules/liquidityPool.js#L241-L248

**Comment by remote-gildor** [comment]
Oh, I see, the timestamp is automatically converted into a user's time, so no need for any check at all. I'll remove the "(UTC)" part.
