### ISSUE TITLE
Markets buttons missing

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#36]
Sometimes when changing pages the markets buttons disappear:

![image](https://user-images.githubusercontent.com/2445889/144602921-7fbfdc80-4874-460c-bd89-6e14dfafa636.png)

If I switch back and forth to the "Trade" page, the buttons appear again:

![image](https://user-images.githubusercontent.com/2445889/144602159-4c7d9f9f-1638-496d-9e7b-7fa42fec2da6.png)

Additionaly, see that the **ETH price is being shown along with MATIC options** in the first image. So there must be an issue with the loading of the "Trade" page when switching back and forth pages.

**Comment by remote-gildor** [comment]
@TCGV I'm trying to reproduce this error, but I can't. It works without any glitch for me. May I ask you which RPC URL do you use?

**Comment by TCGV** [comment]
> @TCGV I'm trying to reproduce this error, but I can't. It works without any glitch for me. May I ask you which RPC URL do you use?

I'm using MetaMask chrome extension, not sure if that's what you asked.

I also tried reproducing this error again a few times but wasn't able to. Something I noticed was this error in the console which seems to be related to RPC calls limit:

![image](https://user-images.githubusercontent.com/2445889/144838322-21a6b415-0566-4df5-bce0-829c76e46cf8.png)

**Comment by remote-gildor** [comment]
No, I meant the RPC URL that you can see when you edit a network:

![](https://uploads-ssl.webflow.com/6081ec44cd568126cb60cef5/60e5f35ac3e2e0f6fd2109bb_image-6.png)

Which RPC URL do you have for Polygon? It should be this one: https://polygon-rpc.com/ 

But these nodes can be overwhelmed with traffic from time to time which may cause the error that you mentioned.

**Comment by TCGV** [comment]
> No, I meant the RPC URL that you can see when you edit a network:
> 
> Which RPC URL do you have for Polygon? It should be this one: https://polygon-rpc.com/
> 
> But these nodes can be overwhelmed with traffic from time to time which may cause the error that you mentioned.

This one actually: https://rpc-mainnet.maticvigil.com

**Comment by remote-gildor** [comment]
Can you change it to this one? https://polygon-rpc.com/
