### ISSUE TITLE
User Writable Options

### ISSUE THREAD

**Issue by cinquemb** [DeFiOptions/DeFiOptions-frontend#37]
In order to be able to have OTM available for the default pool and expand what users can do easily, I got started on being able to write covered options in the UI:

https://github.com/cinquemb/DeFiOptions-frontend/commit/125f6dfdd53cd6d9aaa43eda921d61d5d2c30b86

and example of what its like so far is here:

https://cinquemb.github.io/DeFiOptions-frontend/#/trade

Here's how i think the workflows can be like for both calls and puts:

(1a) 
- pulls the amount of underlying (from feed type) from their wallet address, displays writable amount of options (can be used for calls only)
- need to create form for writing covered
           address tkAddr = writeCovered(
	        eth_usd_feed,
	        10 * volumeBase,
	        strikePrice, 
	        maturity,
	        msg.sender
	    )

(1b)
- pulls the amount of stablecoin balance they have (can be used for calls and puts)
- need to get form for calc collateral for amount of options selected
	address eth_usd_feed = address(0x987...);
	uint volumeBase = 1e18;
	uint strikePrice = 1300e18;
	uint maturity = now + 30 days;

	uint collateral = exchange.calcCollateral(
	     feed_address, 
	     10 * volumeBase, 
	     OptionsExchange.OptionType.CALL, 
	     strikePrice, 
	     maturity
	 );
- need to deposit collateral amount + 0.5%
- need to create form for writing option
	        address tkAddr = exchange.writeOptions(
	            eth_usd_feed, 
	            10 * volumeBase, 
	            OptionsExchange.OptionType.CALL, 
	            strikePrice, 
	            maturity,
	            msg.sender
	        );

(2) 
- use sell form on myoption comopenent from within options component?

**Comment by TCGV** [comment]
Complementing Cinque's proposal:

In the first workflow (1a) it will also be required to approve the OptionsExchange's address for transfering the underlying to the exchange's vault, like implemented in this unit test function:

- https://github.com/DeFiOptions/DeFiOptions-core/blob/2bbf6a6c7500eec88897e4cdf644bbc02648d052/test/finance/OptionsExchange/TestCoveredOption.sol#L235-L253

Polygon and Kovan feeds addresses are available here:

- https://docs.defioptions.org/coding-reference/addresses

Function to get address of underlying asset for a feed:

- [UnderlyingFeed.getUnderlyingAddr()](https://github.com/DeFiOptions/DeFiOptions-core/blob/2bbf6a6c7500eec88897e4cdf644bbc02648d052/contracts/interfaces/UnderlyingFeed.sol#L7)

**Comment by remote-gildor** [comment]
Hey, the UI looks good!

I tried doing a sell, but I got the `contract object doesn't have address set yet` error on line 631. This is because there's no option.address when you create a contract in line 628 (in the `approveAllowanceOption()` function:

```javascript
const optionContract = new component.getWeb3.eth.Contract(OptionTokenContractJson.abi, this.option.address);
```

The option object only has two fields in this component: `symbol` and `strike`. 

This data comes from the `fetchSymbolsList` function in store/modules/liquidityPool.js where we have the BUY operation set as default (lines 98 and 99) - not sure if this is a separate problem, or not:

```javascript
const operation = { BUY: "1" }
let symbolsRaw = await state.contract.methods.listSymbols(operation.BUY).call();
```

In the pool smart contract, the listSymbols function is here: https://github.com/DeFiOptions/DeFiOptions-core/blob/2bbf6a6c7500eec88897e4cdf644bbc02648d052/contracts/pools/LiquidityPool.sol#L251

The problem is that this `listSymbols` function **does not return the option address**, which makes it then difficult to create an Option Token contract in the frontend...

The error happens in the function that tries to get Option Token approval. Is this approval really necessary, or is there another way?

**Comment by cinquemb** [comment]
We can get the address for the option contract if we have the symbol like this: https://github.com/DeFiOptions/DeFiOptions-core/blob/2bbf6a6c7500eec88897e4cdf644bbc02648d052/contracts/finance/OptionsExchange.sol#L451-L456

`options_exchange.functions.resolveToken("BTC/USD-EP-147e18-1623989786").call()`

I just haven't done this in the UI yet (as well as a bunch of other stuff)

**Comment by remote-gildor** [comment]
Great! So what's next, do we wait on @TCGV to add the missing contract function(s), or do we have to first decide what approach to take?

**Comment by TCGV** [comment]
> Great! So what's next, do we wait on @TCGV to add the missing contract function(s), or do we have to first decide what approach to take?

Hey @remote-gildor, as Cinque pointed out, the function already exists. You just need to pass an options symbol to the OptionsExchange `resolveToken` function to get the option token contract address:

![image](https://user-images.githubusercontent.com/2445889/145741735-be5926de-d654-4e04-858e-40e76960ad5b.png)

Try it here: https://polygonscan.com/address/0x69b38e5cd783cbeeb06e11b4ad29a95af14dbcc9#readProxyContract

(option token contracts are being created before they are added to the pool)

**Comment by cinquemb** [comment]
> Great! So what's next, do we wait on @TCGV to add the missing contract function(s), or do we have to first decide what approach to take?


Well, the last thing i've done was add a fuction to get the underlying balance (https://github.com/cinquemb/DeFiOptions-frontend/commit/c5eb07c0eb3c98aecad5fde8d1f3a19527a2d8db)

Now what left is to:
- compute the amount of options that can be used based on the underlying balance
- write covered function 
- ui for approving and writing covered calls
- computing collataral reqs for a given stablecoin/exchange balance selected
- ui for approving and depositing collateral (if exchange balance is not selected)
- write options function and ui for that

Not sure how the extra UI will look like within trade screen after a particular option is selected to sell (and not sure if the mocks [where are the mocks?] cover it).
Also not sure when I'll be able to get to all of it, mostly been chipping away at stuff slowly when i have some free time.

**Comment by remote-gildor** [comment]
Mocks are here: https://www.figma.com/file/AFWN8qL29z8upMw8FcadR8/DEOX-v1.0

But they don't cover selling options...

Maybe we should start by first drawing the mockups for selling options (just wireframes, not the real design) and then go into implementing them. What do you think?

**Comment by remote-gildor** [comment]
> Hey @remote-gildor, as Cinque pointed out, the function already exists. You just need to pass an options symbol to the OptionsExchange `resolveToken` function to get the option token contract address

Yeah I didn't mean that function. I meant a potential new one (if needed at all) for selling options.

**Comment by cinquemb** [comment]
> > Hey @remote-gildor, as Cinque pointed out, the function already exists. You just need to pass an options symbol to the OptionsExchange `resolveToken` function to get the option token contract address
> 
> Yeah I didn't mean that function. I meant a potential new one (if needed at all) for writing options.

Yeah, all the functions are already there in the exchange contract, so all thats really needed is just front end stuff.
