### ISSUE TITLE
Cannot buy with exchange balance

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#7]
I tried to buy an option using my exchange balance in the frontend app and the transaction resulted in an error:

- https://kovan.etherscan.io/tx/0x74895ceebf8202b5dfe4a0d53ebc33a362535d766bc1801121f19bc71261d814

When testing from my console app it works:

- https://kovan.etherscan.io/tx/0x8c98bc4bd79be61daf1ef41e366b12ab3c9a6c3b2a01e3244be12063a961899d

This must be the result of the latest re-deployment of core contracts, in which the following function no longer accepts the exchange's address:

    buy(string optSymbol, uint256 price, uint256 volume, address token, uint256 maxValue, uint256 deadline, uint8 v, bytes32 r, bytes32 s)

And the following function should be called instead:

    buy(string optSymbol, uint256 price, uint256 volume, address token)

**Comment by remote-gildor** [comment]
Fixed in this commit: https://github.com/DeFiOptions/DeFiOptions-frontend/commit/e42f1383382377ff334844349497ea9412ba7282
