### ISSUE TITLE
Preserve options table selection

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-frontend#8]
**1)** In the "Trade" page, when browsing available options to buy I may select the following (ETH - PUT):

![image](https://user-images.githubusercontent.com/2445889/121183433-72866200-c83a-11eb-8db7-c030b8b41222.png)

**2)** Then, If navigate to another page, for instance the "Invest" page, it loads like the following:

![image](https://user-images.githubusercontent.com/2445889/121183588-9f3a7980-c83a-11eb-9bac-05a997bb977e.png)

**3)** Now, if I go back to the "Trade" page it will initially show the previously selected options (ETH - PUT) and then subtly reload the default selection (ETH - CALL):

![image](https://user-images.githubusercontent.com/2445889/121183918-f4768b00-c83a-11eb-9b88-f4f7fc8cb75a.png)

This behavior may bring confusion to the app users. For instance, I was intending to buy PUT options and accidentatly bought CALL options because I didn't notice this subtle change at first, only after the transaction completed.

My proposal is to always preseve the options table selection to prevent this issue from happening, just like [sushiswap](https://app.sushi.com/swap) preserves the tokens selection when shifting from the "swap" tab to the "liquidity" tab and then swithcing back to the "swap" tab.

**Comment by remote-gildor** [comment]
Good point, will add support for preserving this state 👍

**Comment by remote-gildor** [comment]
Completed: https://github.com/DeFiOptions/DeFiOptions-frontend/commit/a72d440b846571ddb96b0bd633ea5e1b54c2496b
